amlt logs exotic-snapper -o /data/xh
amlt logs bias_experiment_vit -o /data/xh
amlt logs bias_experiment_sup -o /data/xh
amlt logs transprobe_experiment_sup -o /data/xh
amlt logs fintuning_group_experiment_vit -o /data/xh
amlt logs fintuning_group_experiment_sup -o /data/xh
amlt logs transprobe_experiment_vit -o /data/xh
amlt logs cswin_experiment_vit -o /data/xh
amlt logs positionbias_experiment_vit -o /data/xh
amlt logs transprobe_experiment -o /data/xh
amlt logs attention_experiment_vit -o /data/xh
amlt logs ladapter_experiment_vit -o /data/xh
amlt logs attention_experiment -o /data/xh
amlt logs lora_experiment_sup_fix -o /data/xh
amlt logs lora_experiment_sup -o /data/xh
amlt logs lorafix_experiment_vit -o /data/xh
amlt logs lora_experiment_vit -o /data/xh
amlt logs adapter_experiment_vit -o /data/xh
amlt logs slayernorm_experiment -o /data/xh
amlt logs finetune_experiment_100_lr -o /data/xh
amlt logs finetune_experiment_100_sup_lr -o /data/xh
amlt logs first_adapter_experiment -o /data/xh
amlt logs layernorm_experiment -o /data/xh
amlt logs finetune_experiment-100 -o /data/xh
